sudo: false
language: c
compiler:
  - gcc
addons:
  apt:
    packages:
    - libssl-dev
    - libevent-dev
    - libexpat-dev
    - clang
script:
  - ./configure --enable-debug
  - make
  - make test
  - cd testdata; ../testcode/mini_tdir.sh exe clang-analysis.tdir ; grep -e "warning:" -e "error:" result.clang-analysis
